name: Java CI

on:
  workflow_dispatch:
    inputs:
      RESTART_TIME:
        description: 'Restarts server in given seconds'
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Set up PATH
      run: echo "$HOME/.bin" >> ${GITHUB_PATH}
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew --no-daemon
    - name: Deploy the L2J Server
      run: deploy-server.sh ${GITHUB_REF_NAME}
    - name: Restart the L2J Server
      if: github.event.inputs.RESTART_TIME
      run: |
          restart_login.sh
          restart_server.sh ${GITHUB_REF_NAME} ${{github.event.inputs.RESTART_TIME}}
