name: Java CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Set up PATH
      run: echo "$HOME/.bin" >> $GITHUB_PATH
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew --no-daemon
    - name: Deploy the L2J Server
      run: deploy-server.sh ${GITHUB_REF_NAME}
